import type { PromptBudgetProfile } from "@ai-novel/shared/types/chapterRuntime";

export const NOVEL_PROMPT_BUDGETS = {
  directorCandidates: 1200,
  directorCandidatePatch: 1200,
  directorBookContract: 1400,
  directorBlueprint: 2400,
  storyMacroDecomposition: 1800,
  storyMacroFieldRegeneration: 1600,
  volumeStrategy: 1800,
  volumeStrategyCritique: 1800,
  volumeSkeleton: 2000,
  volumeBeatSheet: 1600,
  volumeChapterList: 1600,
  volumeChapterDetail: 2400,
  volumeRebalance: 1600,
  chapterWriter: 2600,
  chapterAcceptance: 1200,
  chapterArtifactDelta: 1400,
  chapterEditorWorkspaceDiagnosis: 1400,
  chapterEditorUserIntent: 900,
  chapterEditorRewrite: 1400,
  chapterLightAudit: 900,
  chapterReview: 2600,
  chapterRepair: 2200,
  chapterSummary: 1000,
} as const;

export const RUNTIME_PROMPT_BUDGET_PROFILES: PromptBudgetProfile[] = [
  {
    promptId: "novel.chapter.writer",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterWriter,
    preferredGroups: [
      "chapter_boundary",
      "chapter_mission",
      "previous_chapter_tail",
      "timeline_context",
      "previous_chapter_hook",
      "character_hard_facts",
      "payoff_directives",
      "style_contract",
      "volume_window",
      "participant_subset",
      "local_state",
      "open_conflicts",
      "recent_chapters",
    ],
    dropOrder: [
      "rag_facts",
      "world_rules",
      "continuation_constraints",
      "opening_constraints",
    ],
  },
  {
    promptId: "novel.chapter.acceptance_assessment",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterAcceptance,
    preferredGroups: [
      "chapter_mission",
      "structure_obligations",
      "character_hard_facts",
      "local_state",
      "style_contract",
      "open_conflicts",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
      "world_rules",
      "historical_issues",
    ],
  },
  {
    promptId: "novel.chapter.artifact_delta.extract",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterArtifactDelta,
    preferredGroups: [
      "chapter_mission",
      "local_state",
      "character_hard_facts",
      "payoff_directives",
      "open_conflicts",
    ],
    dropOrder: [
      "recent_chapters",
      "world_rules",
      "historical_issues",
      "participant_subset",
    ],
  },
  {
    promptId: "audit.chapter.light",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterLightAudit,
    preferredGroups: [
      "chapter_mission",
      "structure_obligations",
      "character_hard_facts",
      "local_state",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
      "historical_issues",
      "world_rules",
    ],
  },
  {
    promptId: "audit.chapter.full",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterReview,
    preferredGroups: [
      "chapter_mission",
      "structure_obligations",
      "character_hard_facts",
      "world_rules",
      "historical_issues",
    ],
    dropOrder: [
      "rag_facts",
      "recent_chapters",
      "participant_subset",
    ],
  },
  {
    promptId: "novel.review.repair",
    maxTokensBudget: NOVEL_PROMPT_BUDGETS.chapterRepair,
    preferredGroups: [
      "style_contract",
      "repair_issues",
      "chapter_mission",
      "previous_chapter_tail",
      "repair_boundaries",
      "character_hard_facts",
      "world_rules",
    ],
    dropOrder: [
      "recent_chapters",
      "participant_subset",
      "continuation_constraints",
    ],
  },
];
